name: C & C++ rules
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./pleasew test -e e2e --profile ${{ matrix.compiler }}
      - name: Run e2e test
        run: ./pleasew test -i e2e --profile ${{ matrix.compiler }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        compiler:
          - gcc
          - clang
        exclude:
          # only do clang on macos
          - os: macos-latest
            compiler: gcc
